name: phpunit
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions:
        - '7.4'
        - '8.0'
        
    env:
      S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
      S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
      S3_BUCKET: test.macbre.net

    steps:
    - name: Install and test s3cmd
      run: |
        sudo apt-get install s3cmd
        s3cmd --version

        s3cmd --access_key=${S3_ACCESS_KEY} --secret_key=${S3_SECRET_KEY} ls s3://${S3_BUCKET}/

    - name: Checkout
      uses: actions/checkout@v2
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}

    - name: Get composer cache directory
      id: composer-cache-directory
      run: |
        composer config cache-dir
        echo "::set-output name=dir::$(composer config cache-dir)"
    - name: composer cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.composer-cache-directory.outputs.dir }}
        key: php-${{ matrix.php-versions }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          php-${{ matrix.php-versions }}-composer

    - name: Compose setup
      run: |
        composer validate
        composer check-platform-reqs
        composer install --no-interaction

    - name: Test the code
      run: |
        composer exec phpunit
